export default {
    graph: {
        directed: false,
        hborder: 10,
        vborder: 10,
        color: 0x000000,
        alpha: 1,
        alpha1: 0.5,
        alpha2: 0.5,
        kscale: 1,
        vscale: 1,
        vfamily: 'monospace',
        lscale: 5,
        lfamily: 'monospace',
    },
    vertex: {
        size: 10,
        color: 0xffffff,
        shape: 'circle',
        bwidth: 0,
        bcolor: 0x808080,
        kfamily: 'sans-serif',
    },
    edge: {
        width: 1,
        color: 0xffffff,
        alpha: 0.5,
        curve1: 1,
        curve2: 1,
        lparam: 0.5,
    },
};
